version: '3'
services:
  wnc-fe:
    build: .
    volumes:
      - .:/user/app/src
      - .nginx/nginx.conf:/user/app/demo
    image: ntantai21810/wnc
  nginx:
    image: nginx:alpine
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    entrypoint: ['nginx', '-g', 'daemon off;']
    volumes:
      - /.nginx:/etc/nginx
    depends_on:
      - wnc-fe
